
#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/yuandra/2016-04-07-data-acquisition-cleaning"
workshop_site   : "http://yuandra.github.io/2016-04-07-data-acquisition-cleaning"
#--------------------------------------------------------------------------------
# Standard Data Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
dc_blog        : "http://datacarpentry.github.io/blog"
dc_contact     : "admin@datacarpentry.org"
dc_github      : "http://github.com/datacarpentry"
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
#dc_lessons     : "http://software-carpentry.org/v5/novice"
dc_site        : "http://datacarpentry.org"
dc_twitter     : "http://twitter.com/datacarpentry"
#swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : redcarpet
redcarpet       :
  extensions    : ["tables"]
exclude         : [tools]
